services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --set redpanda.auto_create_topics_enabled=true
    ports:
      - "19092:19092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - sentinel-net

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=lumen_db
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=lumenlog2026
    mem_limit: 1g
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sentinel-net

  dev-shell:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - .:/workspace:cached
    network_mode: service:redpanda 
    tty: true
    stdin_open: true

  ingestor:
    image: golang:1.26
    container_name: lumen-ingestor
    working_dir: /app
    ports:
      - "9001:9001"
    volumes:
      - .:/app
    depends_on:
      redpanda:
        condition: service_started
      clickhouse:
        condition: service_healthy
      topic-init:
        condition: service_completed_successfully
    command: sh -c "sleep 10 && cd cmd/ingestor && go run main.go"
    networks:
      - sentinel-net
    
  security-agent:
    image: rust:1.88
    container_name: lumen-security-agent
    working_dir: /app
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    command: >
      sh -c "
      apt update &&
      apt install -y cmake pkg-config build-essential protobuf-compiler &&
      cd agent &&
      cargo run
      "
    depends_on:
      - redpanda
    networks:
      - sentinel-net

  alerter:
    image: golang:1.26
    container_name: lumen-alerter
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redpanda
    command: sh -c "cd cmd/alerter && go run main.go"
    networks:
      - sentinel-net

  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.2
    depends_on:
      - redpanda
    networks:
      - sentinel-net
    entrypoint: >
      bash -c "
      sleep 5 &&
      rpk topic create logs-raw --brokers redpanda:9092 || true
      "

volumes:
  clickhouse-data:
  redpanda-data:

networks:
  sentinel-net:
    external: true
    name: sentinel-net